version: "3.9"
services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    image: recipe_app_api:latest
    container_name: recipe_app_api_container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db 
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:
  dev-static-data:

#sudo docker-compose run --rm app sh -c 'flake8'
#sudo docker-compose run --rm app sh -c 'django-admin startproject app .'
#sudo docker-compose run --rm app sh -c "python manage.py test"
#sudo docker-compose run --rm app sh -c "python manage.py startapp core"
#sudo docker volume rm recipe-app-api_dev-db-data
#sudo docker volume ls
#sudo docker-compose run --rm app sh -c "python manage.py createsuperuser"
#admin@yopmail.com
#12345
#sudo docker-compose run --rm app sh -c "python manage.py makemigrations"
#sudo docker-compose run --rm app sh -c "python manage.py migrate"
#sudo docker-compose run --rm app sh -c "python manage.py collectstatic"
#sudo docker-compose -f docker-compose-deploy.yml down
#sudo docker-compose -f docker-compose-deploy.yml up
